#!/bin/dash
#!/bin/sh

#By Jonathan Williams (z5162987) - July 2019

#error checking: existence of .legit
if [ ! -d ".legit" ]
then
   echo "legit-commit: error: no .legit directory containing legit repository exists"
   exit 1
fi

#error check if any commits yet
if [ ! -d ".legit/.0" ]
then
   echo "legit-show: error: your repository does not have any commits yet"
   exit 1
fi


#error checking: usage, 
if [ $# -ne 1 ] || [ ! `echo $1 | egrep ":"` ]
then
   echo "usage: legit-show <commit>:<filename>"
   exit 0
fi

#extract arguments
commit=`echo $1 | cut -d':' -f1`
filename=`echo $1 | cut -d':' -f2`

#error checking: $commit must be the number of an existent commit folder or just an empty string
if [ `echo $commit|egrep "[^0-9]"` ] || ([ ! -d ".legit/.$commit" ] && [ ! $commit = "" ])
then
   echo "legit-show: error: unknown commit '$commit'"
   exit 1
fi 

#$filename must be the name of a file within the correct commit folder or within the index
#if no commit provided, check index
if [ "$commit" = "" ]
then
   if [ ! -f ".legit/.index/$filename" ]
   then
      #check latest commit
      n=-1
      while [ -d ".legit/.$(($n+1))" ]
      do
         n=$(($n+1)) 
      done
      if [ ! -f ".legit/.$n/$filename" ]
      then
         echo "legit-show: error: '$filename' not found in index"
         exit 1
      else
         cat ".legit/.$n/$filename"
      fi
   else
      cat ".legit/.index/$filename"
   fi  
#check commit folder
else
   if [ ! -f ".legit/.$commit/$filename" ]
   then
      echo "legit-show: error: '$filename' not found in commit $commit"
      exit 1
   else
      cat ".legit/.$commit/$filename"
   fi
fi
